### ISSUE TITLE
Change instance name and system dashboard issue

### ISSUE THREAD

**Issue by Bodenhaltung** [systemli/prometheus-jitsi-meet-exporter#21]
How can i change the instance name? I had the name "localhost".

Not exactly fits here, but maybe someone has an idea:
`node_exporter, version 0.15.2+ds (branch: debian/sid, revision: 0.15.2+ds-1)`

Doesn't send the metrics "node_cpu_seconds_total" nor "node_memory_MemFree_bytes". Is there an updated version for the dashboard?

**Comment by 0x46616c6b** [comment]
Hey,

this is related what you define in your `scrape_config` in Prometheus. If you run a single node installation with Jitsi Meet, Jitsi Meet Exporter and Prometheus your Prometheus config will look like:

```yaml
  - job_name: node
    metrics_path: /metrics
    static_configs:
    - targets:
      - localhost:9100
```

The job will extract the instance from the targets. If you want to relabel you can look here https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config.

For example something like this

```yaml
  - job_name: node
    metrics_path: /metrics
    static_configs:
    - targets:
      - localhost:9100
    relabel_configs:
    - source_labels: ["instance"]
      replacement: "<your-instance-name>"
```
