### ISSUE TITLE
Scrape error: Connection refused

### ISSUE THREAD

**Issue by Lithimlin** [systemli/prometheus-jitsi-meet-exporter#70]
I'm getting the following error:
```console
jitsiexporter_1  | scrape error: Get "http://localhost:8888/colibri/stats": dial tcp 127.0.0.1:8888: connect: connection refused
```
I had previously used the very similar [jitsiexporter by xsteadfastx](https://github.com/xsteadfastx/jitsiexporter), however, this broke at some point since v6173 of jitsi. The errors I get with both exporters are identical.

I can use curl on the very same URL and get a result without any issues. I'm not sure what the problem is.

Here is my config:
```yaml
version: '3.7'                                                                  
                                                                                   
services:                                                                          
  jitsiexporter:                                         
    image: systemli/prometheus-jitsi-meet-exporter:latest                      
    restart: unless-stopped                                                     
    ports:                                                                     
      - 9700:9888                             
    command: -videobridge-url http://localhost:8888/colibri/stats              
    networks:                                                                   
      exporter.jitsi:                                                           
                                                                                
networks:                                                                       
  exporter.jitsi:                                                               
    name: exporter.jitsi
```
```yaml
[...]
# Video bridge                                                              
    jvb:                                                                        
        image: jitsi/jvb:${VERSION}                                             
        restart: ${RESTART_POLICY}                                              
        ports:                                                                  
            - '${JVB_PORT}:${JVB_PORT}/udp'                                     
            - '${JVB_TCP_PORT}:${JVB_TCP_PORT}'                                 
            - '${JVB_TCP_MAPPED_API_PORT}:${JVB_TCP_API_PORT}'                  
        volumes:                                                                
            - ${CONFIG}/jvb:/config:Z                                           
        environment:                                                            
            - DOCKER_HOST_ADDRESS                                               
            - ENABLE_COLIBRI_WEBSOCKET                                          
            - ENABLE_OCTO                                                       
            - JVB_AUTH_USER                                                     
            - JVB_AUTH_PASSWORD                                                 
            - JVB_BREWERY_MUC                                                   
            - JVB_PORT                                                          
            - JVB_MUC_NICKNAME                                                  
            - JVB_TCP_HARVESTER_DISABLED                                        
            - JVB_TCP_PORT                                                      
            - JVB_TCP_MAPPED_PORT                                               
            - JVB_STUN_SERVERS                                             
            - JVB_WS_DOMAIN                                                     
            - JVB_WS_SERVER_ID                                                  
            - PUBLIC_URL                                                  
            - COLIBRI_REST_ENABLED                                              
            - SHUTDOWN_REST_ENABLED                                             
            - TZ                                                                
            - XMPP_AUTH_DOMAIN                                                  
            - XMPP_INTERNAL_MUC_DOMAIN                                          
            - XMPP_SERVER                                                       
        depends_on:                                                             
            - prosody                                                           
        networks:                                                               
            meet.jitsi:                                                         
            exporter.jitsi:                                                        
                                                                                
# Custom network so all services can communicate using a FQDN                   
networks:                                                                       
    meet.jitsi:                                                                 
      name: meet.jitsi                                                          
    exporter.jitsi:                                                             
      external: true
```

`.env` variables:
```env
JVB_TCP_API_PORT=8080                                                           
JVB_TCP_MAPPED_API_PORT=8888   

# Optional properties for shutdown api                                          
COLIBRI_REST_ENABLED=true                                                       
SHUTDOWN_REST_ENABLED=true 
```
