### ISSUE TITLE
jvb metrics - json decoding error: invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by dmitry-mightydevops** [systemli/prometheus-jitsi-meet-exporter#93]
I have started receiving prometheus alerts that the prometheus target is missing

This is my jvb POD exporter

```
...CUT...

- command:
      - /prometheus-jitsi-meet-exporter
      - -videobridge-url
      - http://localhost:8080/colibri/stats
      image: docker.io/systemli/prometheus-jitsi-meet-exporter:1.2.0
      imagePullPolicy: IfNotPresent
      name: metrics
      ports:
      - containerPort: 9888
        name: tcp-metrics
        protocol: TCP
      readinessProbe:
        failureThreshold: 3
        httpGet:
          path: /health
          port: 9888
          scheme: HTTP
        initialDelaySeconds: 3
        periodSeconds: 5
        successThreshold: 1
        timeoutSeconds: 1
      resources:
        limits:
          cpu: 20m
          memory: 32Mi
        requests:
          cpu: 10m
          memory: 16Mi
      securityContext:
        runAsUser: 10001
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-n6b9m
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeName: ip-10-120-5-78.us-west-2.compute.internal
    nodeSelector:
      jitsi: "true"
```

```
✗  klo -l app.kubernetes.io/component=jvb -c metrics
json decoding error: invalid character '<' looking for beginning of value
json decoding error: invalid character '<' looking for beginning of value
json decoding error: invalid character '<' looking for beginning of value
json decoding error: invalid character '<' looking for beginning of value
json decoding error: invalid character '<' looking for beginning of value
json decoding error: invalid character '<' looking for beginning of value
json decoding error: invalid character '<' looking for beginning of value
json decoding error: invalid character '<' looking for beginning of value
json decoding error: invalid character '<' looking for beginning of value
json decoding error: invalid character '<' looking for beginning of value


➜ k poo                   
NAME                                 IMG                               PODIP          NODE                                         NODEIP       PORTS                      STATE     QOS          STARTED
jitsi-meet-jicofo-755689bfd9-x65rp   jitsi/jicofo:stable-6865          10.120.6.85    ip-10-120-5-78.us-west-2.compute.internal   10.120.5.78   80                         Running   BestEffort   2022-03-18T06:38:49Z
jitsi-meet-jvb-5bb4c6759d-2m6z4      jitsi/jvb:stable-6865             10.120.6.87    ip-10-120-5-78.us-west-2.compute.internal   10.120.5.78   30000                      Running   Burstable    2022-03-19T00:54:55Z
jitsi-meet-prosody-0                 jitsi/prosody:stable-6865         10.120.7.70    ip-10-120-5-78.us-west-2.compute.internal   10.120.5.78   5222,5269,5347,5280,5281   Running   BestEffort   2022-03-18T06:38:58Z
jitsi-meet-web-568c784d8b-nv8vr      jitsi/web:stable-6865             10.120.7.127   ip-10-120-5-78.us-west-2.compute.internal   10.120.5.78   80,443                     Running   BestEffort   2022-03-18T06:38:49Z
utils                                praqma/network-multitool:fedora   10.120.2.236   ip-10-120-1-2.us-west-2.compute.internal    10.120.1.2    <none>                     Running   BestEffort   2022-03-19T00:38:39Z

```

so what can I do to fix it?
